AllCops:
  Include:
    # - lib/adiwg/mdtranslator/readers/iso19115_3/**/*.rb
    - lib/adiwg/mdtranslator/readers/iso19115_2_datagov/**/*.rb
    - lib/adiwg/mdtranslator/internal/module_utils.rb
    # - test/readers/iso19115_3/**/*.rb
    - test/readers/iso19115_2_datagov/**/*.rb
  Exclude:
    - bin/*
    - vendor/**/*

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Width: 2

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/VariableName:
  EnforcedStyle: camelCase

Style/ClassVars:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false